[build-system]
requires = ["setuptools>=77", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ovos-wikipedia-plugin"
dynamic = ["version"]
description = "OVOS Wikipedia plugin"
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "ovos-utils>=0.7.0,<1.0.0",
    "ovos-plugin-manager>=2.6.1a1,<3.0.0",
    "ovos-bus-client>=1.0.1",
    "rapidfuzz",
    "pydantic",
    "requests"
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-timeout",
    "ovoscope",
    "ovos-persona>=0.9.0a3",
]

[project.entry-points."opm.agents.retrieval"]
ovos-wikipedia-plugin = "ovos_wikipedia:WikipediaRetrievalEngine"

[project.entry-points."opm.agents.toolbox"]
ovos-wikipedia-tool = "ovos_wikipedia:WikipediaToolbox"

[tool.pytest.ini_options]
timeout = 600

[tool.setuptools.dynamic]
version = {attr = "ovos_wikipedia.version.__version__"}
