# auto add labels to PRs
on:
  pull_request_target:
    types: [ opened, edited ]
name: conventional-release-labels
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: bcoe/conventional-release-labels@b503ca473654e07521c051628c5f1f969e7436da  # v1
